<img src="https://upload.wikimedia.org/wikipedia/commons/1/1a/NumPy_logo.svg" alt="NumPy Logo" width="200" height="80">

In [1]:
import numpy as np

In [2]:
a = np.array([0, 1, 2, 3])
print(a)

print(np.arange(10))

[0 1 2 3]
[0 1 2 3 4 5 6 7 8 9]


In [9]:
L = range(1000)
%timeit [i**2 for i in L]

132 μs ± 4.75 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [8]:
a = np.arange(1000)
%timeit a**2

2.36 μs ± 86.8 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [11]:
# 1D
a = np.array([0, 1, 2, 3])
print(a)

[0 1 2 3]


In [14]:
print(a.ndim)
print(a.shape)
print(len(a))

1
(4,)
4


In [ ]:
# 2D
b = np.array([[0, 1, 2], [3, 4, 5]])
print(b)
print(b.ndim)
print(b.shape)
print(len(b))

[[0 1 2]
 [3 4 5]]
2
(2, 3)
2


In [16]:
# 3D
c = np.array([[[0, 1], [2, 3]], [[4, 5], [6, 7]]])
print(c)
print(c.ndim)
print(c.shape)
print(len(c))

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
3
(2, 2, 2)
2


In [17]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [18]:
b = np.arange(1, 10, 2)
print(b)

[1 3 5 7 9]


In [19]:
a = np.linspace(0, 1, 6)
print(a)

[0.  0.2 0.4 0.6 0.8 1. ]


In [20]:
a = np.ones((3, 3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [21]:
b = np.zeros((3, 3))
print(b)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [22]:
e = np.eye(3)
print(e)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [23]:
e = np.eye(3, 2)
print(e)

[[1. 0.]
 [0. 1.]
 [0. 0.]]


In [25]:
a = np.diag([1, 2, 3, 4])
print(a)
print(np.diag(a))

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
[1 2 3 4]


In [27]:
a = np.random.rand(4)
print(a)

a = np.random.randn(4)
print(a)

[0.5431569  0.25357602 0.33974741 0.73417697]
[ 0.22120192 -1.52852501  0.82384324  0.75378636]


In [28]:
a = np.arange(10)
print(a.dtype)

int64


In [31]:
a = np.arange(10, dtype='float64')
print(a)
print(a.dtype)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
float64


In [32]:
a = np.zeros((3, 3))
print(a)
print(a.dtype)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
float64


In [33]:
d = np.array([1+2j, 2+4j])
print(d)
print(d.dtype)

[1.+2.j 2.+4.j]
complex128


In [34]:
b = np.array([True, False, True, False])
print(b)
print(b.dtype)

[ True False  True False]
bool


In [35]:
s = np.array(["Mash", "Safa", "Ray", "Babe"])
print(s)
print(s.dtype)

['Mash' 'Safa' 'Ray' 'Babe']
<U4


In [36]:
a = np.arange(10)
print(a)
print(a[5])

[0 1 2 3 4 5 6 7 8 9]
5


In [40]:
a = np.diag([1, 2, 3])
print(a)
print(a[0, 0])
print(a[1, 1])
print(a[2, 2])

a[2, 1] = 5
print(a)

[[1 0 0]
 [0 2 0]
 [0 0 3]]
1
2
3
[[1 0 0]
 [0 2 0]
 [0 5 3]]


In [42]:
a = np.arange(10)
print(a)
print(a[1:8:2])

[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7]


In [45]:
a = np.arange(10)
a[5:] = 10
print(a)

[ 0  1  2  3  4 10 10 10 10 10]


In [47]:
b = np.arange(5)
a[5:] = b[::-1]
print(a)

[0 1 2 3 4 4 3 2 1 0]


In [48]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [49]:
b = a[::2]
print(b)

[0 2 4 6 8]


In [50]:
np.shares_memory(a, b)

True

In [52]:
b[0] = 10
print(b)
print(a)

[10  2  4  6  8]
[10  1  2  3  4  5  6  7  8  9]


In [54]:
a = np.arange(10)
c = a[::2].copy()

print(a)
print(c)
print(np.shares_memory(a,c))

c[0] = 10
print(a)
print(c)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
False
[0 1 2 3 4 5 6 7 8 9]
[10  2  4  6  8]


In [56]:
a = np.random.randint(0, 20, 15)
print(a)

[19 10 16 15 17  4 18 16  4 12  7  3  0  3  9]


In [57]:
mask = (a % 2 == 0)

extract_from_a = a[mask]
print(extract_from_a)

[10 16  4 18 16  4 12  0]


In [58]:
a[mask] = -1
print(a)

[19 -1 -1 15 17 -1 -1 -1 -1 -1  7  3 -1  3  9]


In [64]:
a = np.arange(0, 100, 10)
print(a)
print(a[[2, 3, 2, 4, 2]])
print(a)
a[[9, 7]] = -200
print(a)

[ 0 10 20 30 40 50 60 70 80 90]
[20 30 20 40 20]
[ 0 10 20 30 40 50 60 70 80 90]
[   0   10   20   30   40   50   60 -200   80 -200]


In [66]:
a = np.array([1, 2, 3, 4])
print(a+1)
print(a**2)

[2 3 4 5]
[ 1  4  9 16]


In [69]:
print(a)
b = np.ones(4) + 1
print(b)
print(a-b)
print(a*b)

[1 2 3 4]
[2. 2. 2. 2.]
[-1.  0.  1.  2.]
[2. 4. 6. 8.]


In [75]:
c = np.diag([1, 2, 3, 4])
print(c)
print("*********")
print(c * c)
print("*********")
print(c.dot(c))

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
*********
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
*********
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [77]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 2, 2, 4])
print(a == b)
print(a > b)

[False  True False  True]
[False False  True False]


In [79]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 2, 2, 4])
c = np.array([1, 2, 3, 4])

print(np.array_equal(a, b))
print(np.array_equal(a, c))

False
True


In [81]:
a = np.array([1, 1, 0, 0], dtype=bool)
b = np.array([1, 0, 1, 0], dtype=bool)

print(np.logical_or(a,b))
print(np.logical_and(a,b))

[ True  True  True False]
[ True False False False]


In [84]:
a = np.arange(5)
print(np.sin(a))
print(np.log(a))
print(np.exp(a))

[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025 ]
[      -inf 0.         0.69314718 1.09861229 1.38629436]
[ 1.          2.71828183  7.3890561  20.08553692 54.59815003]


C:\Users\mashf\AppData\Local\Temp\ipykernel_6412\4263942336.py:3: RuntimeWarning: divide by zero encountered in log
  print(np.log(a))


In [85]:
a = np.arange(4)
print(a + np.array([1, 2]))

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

In [86]:
x = np.array([1, 2, 3, 4])
print(np.sum(x))

10


In [87]:
x = np.array([
    [1, 1],
    [2, 2]
])

print(x)
print(x.sum(axis=0))
print(x.sum(axis=1))

[[1 1]
 [2 2]]
[3 3]
[2 4]


In [88]:
x = np.array([1, 2, 3, 4])
print(x.min())
print(x.max())
print(x.argmin())
print(x.argmax())

1
4
0
3


In [90]:
b = [True, True, False]
print(np.all(b))
print(np.any(b))

False
True


In [93]:
a = np.zeros((50, 50))
print(a)
print(np.any(a != 0))
print(np.all(a == a))

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
False
True


In [98]:
a = np.array([1, 2, 3, 2])
b = np.array([2, 2, 3, 2])
c = np.array([6, 4, 4, 5])

print(((a <= b) & (b <= c)).all())

True


In [ ]:
x = np.array([1, 2, 3, 1])
y = np.array([[1, 2, 3], [5, 6, 1]])

print(x.mean())     # Mean: the average value of all elements in x
print(np.median(x))     # Median: the middle value when the elements of x are sorted
print(np.median(y, axis=-1))
print(x.std())      # Standard Deviation: how spread out the values are from the mean.

1.75
1.5
[2. 5.]
0.82915619758885


In [102]:
# Load Data
data = np.loadtxt('Materials/populations.txt')
print(data)
print(data.T)

[[ 1900. 30000.  4000. 48300.]
 [ 1901. 47200.  6100. 48200.]
 [ 1902. 70200.  9800. 41500.]
 [ 1903. 77400. 35200. 38200.]
 [ 1904. 36300. 59400. 40600.]
 [ 1905. 20600. 41700. 39800.]
 [ 1906. 18100. 19000. 38600.]
 [ 1907. 21400. 13000. 42300.]
 [ 1908. 22000.  8300. 44500.]
 [ 1909. 25400.  9100. 42100.]
 [ 1910. 27100.  7400. 46000.]
 [ 1911. 40300.  8000. 46800.]
 [ 1912. 57000. 12300. 43800.]
 [ 1913. 76600. 19500. 40900.]
 [ 1914. 52300. 45700. 39400.]
 [ 1915. 19500. 51100. 39000.]
 [ 1916. 11200. 29700. 36700.]
 [ 1917.  7600. 15800. 41800.]
 [ 1918. 14600.  9700. 43300.]
 [ 1919. 16200. 10100. 41300.]
 [ 1920. 24700.  8600. 47300.]
 [ 1920. 24700.  8600. 47300.]]
[[ 1900.  1901.  1902.  1903.  1904.  1905.  1906.  1907.  1908.  1909.
   1910.  1911.  1912.  1913.  1914.  1915.  1916.  1917.  1918.  1919.
   1920.  1920.]
 [30000. 47200. 70200. 77400. 36300. 20600. 18100. 21400. 22000. 25400.
  27100. 40300. 57000. 76600. 52300. 19500. 11200.  7600. 14600. 16200.
  24700. 247

In [104]:
year , hares, lynxes, carrots = data.T
print(year)
print(hares)
print(lynxes)
print(carrots)

[1900. 1901. 1902. 1903. 1904. 1905. 1906. 1907. 1908. 1909. 1910. 1911.
 1912. 1913. 1914. 1915. 1916. 1917. 1918. 1919. 1920. 1920.]
[30000. 47200. 70200. 77400. 36300. 20600. 18100. 21400. 22000. 25400.
 27100. 40300. 57000. 76600. 52300. 19500. 11200.  7600. 14600. 16200.
 24700. 24700.]
[ 4000.  6100.  9800. 35200. 59400. 41700. 19000. 13000.  8300.  9100.
  7400.  8000. 12300. 19500. 45700. 51100. 29700. 15800.  9700. 10100.
  8600.  8600.]
[48300. 48200. 41500. 38200. 40600. 39800. 38600. 42300. 44500. 42100.
 46000. 46800. 43800. 40900. 39400. 39000. 36700. 41800. 43300. 41300.
 47300. 47300.]


In [105]:
populations = data[:, 1:]
print(populations)

[[30000.  4000. 48300.]
 [47200.  6100. 48200.]
 [70200.  9800. 41500.]
 [77400. 35200. 38200.]
 [36300. 59400. 40600.]
 [20600. 41700. 39800.]
 [18100. 19000. 38600.]
 [21400. 13000. 42300.]
 [22000.  8300. 44500.]
 [25400.  9100. 42100.]
 [27100.  7400. 46000.]
 [40300.  8000. 46800.]
 [57000. 12300. 43800.]
 [76600. 19500. 40900.]
 [52300. 45700. 39400.]
 [19500. 51100. 39000.]
 [11200. 29700. 36700.]
 [ 7600. 15800. 41800.]
 [14600.  9700. 43300.]
 [16200. 10100. 41300.]
 [24700.  8600. 47300.]
 [24700.  8600. 47300.]]


In [106]:
print(populations.std(axis=0))

[20510.72285577 16062.59514555  3402.79722076]


In [107]:
print(np.argmax(populations, axis=1))

[2 2 0 0 1 1 2 2 2 2 2 2 0 0 0 1 2 2 2 2 2 2]


In [ ]:
a = np.tile(np.arange(0, 40, 10), (3, 1))
print(a)

print("*****************")

a = a.T
print(a)

[[ 0 10 20 30]
 [ 0 10 20 30]
 [ 0 10 20 30]]
*****************
[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]


In [114]:
b = np.array([0, 1, 2])
print(b)

[0 1 2]


In [115]:
print(a+b)

[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


In [119]:
a = np.arange(0, 40, 10)
print(a)
print(a.shape)
a = a[:, np.newaxis]
print(a)
print(a.shape)

[ 0 10 20 30]
(4,)
[[ 0]
 [10]
 [20]
 [30]]
(4, 1)


In [121]:
print(a)
print(b)
print(a+b)

[[ 0]
 [10]
 [20]
 [30]]
[0 1 2]
[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


In [124]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)
print(a.ravel())
print(a.T)
print(a.T.ravel())

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[[1 4]
 [2 5]
 [3 6]]
[1 4 2 5 3 6]


In [125]:
print(a.shape)
print(a)

(2, 3)
[[1 2 3]
 [4 5 6]]


In [126]:
b = a.ravel()
print(b)
b = b.reshape((2, 3))
print(b)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [127]:
b[0, 0] = 100
print(b)
print(a)

[[100   2   3]
 [  4   5   6]]
[[100   2   3]
 [  4   5   6]]


In [131]:
a = np.zeros((3,2))
print(a)
b = a.T.reshape(3*2)
b[0] = 100
print(b)
print(a)

[[0. 0.]
 [0. 0.]
 [0. 0.]]
[100.   0.   0.   0.   0.   0.]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [132]:
z = np.array([1, 2, 3])
print(z)

[1 2 3]


In [133]:
print(z[:, np.newaxis])

[[1]
 [2]
 [3]]


In [135]:
a = np.arange(4*3*2).reshape(4, 3, 2)
print(a)
print(a.shape)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]
(4, 3, 2)


In [136]:
print(a[0, 2, 1])

5


In [139]:
a = np.arange(4)
b = a.resize((8,))
print(a)

ValueError: cannot resize an array that may be referenced by another object.
It is possible that this is a false positive.
If you are sure that the array is uniquely referenced, set refcheck=False.

In [141]:
a = np.array([[5, 4, 6], [2, 3, 2]])
b = np.sort(a, axis=1)
print(b)
a.sort(axis=1)
print(a)

[[4 5 6]
 [2 2 3]]
[[4 5 6]
 [2 2 3]]


In [143]:
a = np.array([4, 3, 2, 1])
j = np.argsort(a)
print(j)
print(a[j])

[3 2 1 0]
[1 2 3 4]
