<img src="https://upload.wikimedia.org/wikipedia/commons/1/1a/NumPy_logo.svg" alt="NumPy Logo" width="200" height="80">

#### NumPy Arrays

**python objects:** 

1. high-level number objects: integers, floating point
2. containers: lists (costless insertion and append), dictionaries (fast lookup)

**Numpy provides:**

1. extension package to Python for multi-dimensional arrays
2. closer to hardware (efficiency)
3. designed for scientific computation (convenience)
4. Also known as array oriented computing

In [1]:
import numpy as np

In [3]:
a = np.array([0, 1, 2, 3, 4, 5])
print(a)

print(np.arange(10))

[0 1 2 3 4 5]
[0 1 2 3 4 5 6 7 8 9]


In [4]:
# Python lists
L = range(1000)
%timeit [i**2 for i in L]

112 μs ± 3.36 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [5]:
a = np.arange(1000)
%timeit a**2

1.89 μs ± 57.8 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


### 1. Creating arrays

** 1.1.  Manual Construction of arrays**

In [6]:
# 1-D

a = np.array([0, 1, 2, 3, 4])
print(a)
a

[0 1 2 3 4]


array([0, 1, 2, 3, 4])

In [7]:
# Dimensions
a.ndim

1

In [8]:
# shape
a.shape

(5,)

In [9]:
len(a)

5

In [ ]:
# 2D 3D
b = np.array([[0, 1, 2], [3, 4, 5]])
b

[[0 1 2]
 [3 4 5]]


array([[0, 1, 2],
       [3, 4, 5]])

In [12]:
b.ndim

2

In [13]:
b.shape

(2, 3)

In [14]:
len(b)

2

In [15]:
c = np.array([[[0, 1], [2, 3]], [[4, 5], [6, 7]]])
c

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [16]:
c.ndim

3

In [17]:
c.shape

(2, 2, 2)

** 1.2  Functions for creating arrays**

In [ ]:
# arange
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
b = np.arange(1, 10, 2)
b

array([1, 3, 5, 7, 9])

In [20]:
# linspace

a = np.linspace(0, 1, 6)
a

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [ ]:
# common arrays

a = np.ones((3, 3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [24]:
b = np.zeros((3, 3))
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [27]:
c = np.eye(3)
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
c = np.eye(3, 3)
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
# diag
a = np.diag([1, 2, 3, 4, 5])
a

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [31]:
a = np.random.rand(4)
a

array([0.39537775, 0.70692584, 0.43737259, 0.69393171])

### 2. Basic DataTypes

In [32]:
a = np.arange(10)
a.dtype

dtype('int64')

In [33]:
a = np.arange(10, dtype='float64')
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [34]:
a = np.zeros((3, 3))
print(a)
a.dtype

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


dtype('float64')

In [35]:
d = np.array([1+2j, 2+4j])
print(d.dtype)
d.dtype

complex128


dtype('complex128')

In [36]:
b = np.array([True, False, True, False])
print(b.dtype)

bool


In [37]:
s = np.array(['Mash', 'Ray'])
s.dtype

dtype('<U4')

**Each built-in data type has a character code that uniquely identifies it.**

'b' − boolean

'i' − (signed) integer

'u' − unsigned integer

'f' − floating-point

'c' − complex-floating point

'm' − timedelta

'M' − datetime

'O' − (Python) objects

'S', 'a' − (byte-)string

'U' − Unicode

'V' − raw data (void)

### 3. Indexing and Slicing

**3.1 Indexing**

In [38]:
a = np.arange(10)
print(a[5])

5


In [39]:
a = np.diag([1, 2, 3])
print(a)

print(a[2, 2])


[[1 0 0]
 [0 2 0]
 [0 0 3]]
3


In [40]:
a[2, 1] = 5
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 5, 3]])

**3.2 Slicing**

In [41]:
a = np.arange(10)


In [42]:
a[1:8:2] # [startindex: endindex(exclusive) : step]

array([1, 3, 5, 7])

In [43]:
a = np.arange(10)
a[5:] = 10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [45]:
b = np.arange(5)
print(5)
a[5:] = b[::-1]
print(a)

5
[0 1 2 3 4 4 3 2 1 0]


### 4. Copies and Views

In [47]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
b = a[::2]
b

array([0, 2, 4, 6, 8])

In [49]:
np.shares_memory(a, b)

True

In [50]:
b[0] = 10
b

array([10,  2,  4,  6,  8])

In [51]:
a

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [52]:
a = np.arange(10)
c = a[::2].copy()
c

array([0, 2, 4, 6, 8])

In [53]:
np.shares_memory(a, c)
c[0] = 10
print(c)
print(a)

[10  2  4  6  8]
[0 1 2 3 4 5 6 7 8 9]


### 5. Fancy Indexing

In [54]:
a = np.random.randint(0, 20, 15)
a

array([ 1, 13,  8, 14, 18, 15, 10,  1,  9, 11, 19,  6,  2,  3,  2],
      dtype=int32)

In [55]:
mask = (a % 2 == 0)
mask

array([False, False,  True,  True,  True, False,  True, False, False,
       False, False,  True,  True, False,  True])

In [56]:
extract_from_a = a[mask]
extract_from_a

array([ 8, 14, 18, 10,  6,  2,  2], dtype=int32)

In [58]:
a[mask] = -1
a

array([ 1, 13, -1, -1, -1, 15, -1,  1,  9, 11, 19, -1, -1,  3, -1],
      dtype=int32)

In [59]:
a = np.arange(0, 100, 10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [60]:
a[[2, 3, 2, 4, 2]]

array([20, 30, 20, 40, 20])

In [61]:
a[[9,7]] = -200
print(a)

[   0   10   20   30   40   50   60 -200   80 -200]


### Elementwise Operations

**1. Basic Operations**

**with scalars**

In [62]:
a = np.array([1, 2, 3, 4])
a + 1

array([2, 3, 4, 5])

In [63]:
a * 2

array([2, 4, 6, 8])

In [64]:
a ** 2

array([ 1,  4,  9, 16])

**All arithmetic operates elementwise**

In [65]:
b = np.ones(4) + 1
b

array([2., 2., 2., 2.])

In [66]:
a - b

array([-1.,  0.,  1.,  2.])

In [67]:
a * b

array([2., 4., 6., 8.])

In [68]:
# Matrix Multiplication
c = np.diag([1, 2, 3, 4])

print(c * c)
print("**************")
print(c.dot(c))

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
**************
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [69]:
a = np.array([1, 2, 3, 4])
a = np.array([5, 2, 2, 4])

a == b

array([False,  True,  True, False])

In [70]:
a > b

array([ True, False, False,  True])

In [72]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 2, 2, 4])
c = np.array([1, 2, 3, 4])

print(np.array_equal(a, b))
print(np.array_equal(a, c))

False
True


**Logical Operations**

In [73]:
a = np.array([1, 1, 0, 0], dtype=bool)
b = np.array([1, 0, 1, 0], dtype=bool)

In [74]:
np.logical_or(a,b)

array([ True,  True,  True, False])

In [75]:
np.logical_and(a, b)

array([ True, False, False, False])

**Transacendental functions:**

In [76]:
a = np.arange(5)

In [77]:
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [78]:
np.log(a)

C:\Users\mashf\AppData\Local\Temp\ipykernel_11164\176755284.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [79]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

### Basic Reductions

**computing sums**

In [81]:
x = np.array([1, 2, 3, 4])
np.sum(x)

np.int64(10)

In [83]:
x = np.array([[1, 1], [2, 2]])

In [84]:
x

array([[1, 1],
       [2, 2]])

In [85]:
x.sum(axis=0)

array([3, 3])

In [86]:
x.sum(axis=1)

array([2, 4])

**Other reductions**

In [87]:
x = np.array([1, 3, 2])

In [88]:
x.min()

np.int64(1)

In [89]:
x.max()

np.int64(3)

In [90]:
x.argmin()

np.int64(0)

In [91]:
x.argmax()

np.int64(1)

**Logical Operations**

In [93]:
np.all([True, True, False])

np.False_

In [94]:
np.any([True, False, False])

np.True_

In [96]:
a = np.zeros((50, 50))
np.any(a != 0)

np.False_

In [98]:
np.all(a == a)

np.True_

In [101]:
a = np.array([1, 2, 3, 2])
b = np.array([2, 2, 3, 2])
c = np.array([6, 4, 4, 5])

((a<= b) & (b <= c)).all()

np.True_

**Statistics**

In [102]:
x = np.array([1, 2, 3, 1])
y = np.array([[1, 2, 3], [5, 6, 1]])

In [103]:
print(x)
print(y)

[1 2 3 1]
[[1 2 3]
 [5 6 1]]


In [104]:
x.mean()

np.float64(1.75)

In [105]:
np.median(x)

np.float64(1.5)

In [106]:
np.median(y, axis=-1)

array([2., 5.])

In [107]:
x.std()

np.float64(0.82915619758885)

**Example:**

Data in populations.txt describes the populations of hares and lynxes (and carrots) in northern Canada during 20 years.


In [108]:
data = np.loadtxt('./Materials/populations.txt')

In [109]:
data

array([[ 1900., 30000.,  4000., 48300.],
       [ 1901., 47200.,  6100., 48200.],
       [ 1902., 70200.,  9800., 41500.],
       [ 1903., 77400., 35200., 38200.],
       [ 1904., 36300., 59400., 40600.],
       [ 1905., 20600., 41700., 39800.],
       [ 1906., 18100., 19000., 38600.],
       [ 1907., 21400., 13000., 42300.],
       [ 1908., 22000.,  8300., 44500.],
       [ 1909., 25400.,  9100., 42100.],
       [ 1910., 27100.,  7400., 46000.],
       [ 1911., 40300.,  8000., 46800.],
       [ 1912., 57000., 12300., 43800.],
       [ 1913., 76600., 19500., 40900.],
       [ 1914., 52300., 45700., 39400.],
       [ 1915., 19500., 51100., 39000.],
       [ 1916., 11200., 29700., 36700.],
       [ 1917.,  7600., 15800., 41800.],
       [ 1918., 14600.,  9700., 43300.],
       [ 1919., 16200., 10100., 41300.],
       [ 1920., 24700.,  8600., 47300.]])

In [110]:
year, hares, lynxes, carrots = data.T
print(year)

[1900. 1901. 1902. 1903. 1904. 1905. 1906. 1907. 1908. 1909. 1910. 1911.
 1912. 1913. 1914. 1915. 1916. 1917. 1918. 1919. 1920.]


In [111]:
populations = data[:, 1:]
populations

array([[30000.,  4000., 48300.],
       [47200.,  6100., 48200.],
       [70200.,  9800., 41500.],
       [77400., 35200., 38200.],
       [36300., 59400., 40600.],
       [20600., 41700., 39800.],
       [18100., 19000., 38600.],
       [21400., 13000., 42300.],
       [22000.,  8300., 44500.],
       [25400.,  9100., 42100.],
       [27100.,  7400., 46000.],
       [40300.,  8000., 46800.],
       [57000., 12300., 43800.],
       [76600., 19500., 40900.],
       [52300., 45700., 39400.],
       [19500., 51100., 39000.],
       [11200., 29700., 36700.],
       [ 7600., 15800., 41800.],
       [14600.,  9700., 43300.],
       [16200., 10100., 41300.],
       [24700.,  8600., 47300.]])

In [112]:
populations.std(axis=0)

array([20897.90645809, 16254.59153691,  3322.50622558])

In [113]:
np.argmax(populations, axis=1)

array([2, 2, 0, 0, 1, 1, 2, 2, 2, 2, 2, 2, 0, 0, 0, 1, 2, 2, 2, 2, 2])

### Broadcasting

Basic operations on numpy arrays (addition, etc.) are elementwise

This works on arrays of the same size.
    Nevertheless, It’s also possible to do operations on arrays of different sizes if NumPy can transform these arrays     so that they all have the same size: this conversion is called broadcasting.

The image below gives an example of broadcasting:

![title](./Materials/broadcasting.png)

In [122]:
a = np.tile(np.arange(0, 40, 10), (3, 1))
print(a)

print('-----------')
a = a.T
print(a)

[[ 0 10 20 30]
 [ 0 10 20 30]
 [ 0 10 20 30]]
-----------
[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]


In [123]:
b = np.array([0, 1, 2])

In [124]:
a + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [125]:
a = np.arange(0, 40, 10)
print(a)
print(a.shape)

[ 0 10 20 30]
(4,)


In [126]:
a = a[:, np.newaxis]
print(a)
print(a.shape)

[[ 0]
 [10]
 [20]
 [30]]
(4, 1)


In [127]:
a + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

### Array Shape Manipulation

**Flattening**

In [128]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a.ravel()

array([1, 2, 3, 4, 5, 6])

**Reshaping**

In [133]:
print(a)
print(a.shape)

[[100   2   3]
 [  4   5   6]]
(2, 3)


In [129]:
b = a.ravel()
b

array([1, 2, 3, 4, 5, 6])

In [ ]:
b = b.reshape(2, 3)
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [132]:
b[0,0] = 100

print(b)
print(a)

[[100   2]
 [  3   4]
 [  5   6]]
[[100   2   3]
 [  4   5   6]]


In [135]:
a = np.zeros((3, 2))
print(a)
b = a.T.reshape(3*2)
print(b)
b[0] = 50
print(b)
print(a)


[[0. 0.]
 [0. 0.]
 [0. 0.]]
[0. 0. 0. 0. 0. 0.]
[50.  0.  0.  0.  0.  0.]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


**Adding a Dimension**

Indexing with the np.newaxis object allows us to add an axis to an array

newaxis is used to increase the dimension of the existing array by one more dimension, when used once. Thus,

1D array will become 2D array

2D array will become 3D array

3D array will become 4D array and so on

In [140]:
z = np.array([1, 2, 3])
print(z)
print(z.shape)
print(z.ndim)

[1 2 3]
(3,)
1


In [141]:
print(z[:, np.newaxis])
print(z.shape)
print(z.ndim)

[[1]
 [2]
 [3]]
(3,)
1


In [143]:
a = np.arange(4 * 3 * 2).reshape(4, 3, 2)
print(a)
print(a.shape)
print(a.ndim)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]
(4, 3, 2)
3


In [144]:
a[0, 2, 1]

np.int64(5)

**Resizing**

In [145]:
a = np.arange(4)
a.resize((8,))
a

array([0, 1, 2, 3, 0, 0, 0, 0])

In [ ]:
b = a
a.resize((4,)) 

**Sorting Data**

In [ ]:
#Sorting along an axis:
a = np.array([[5, 4, 6], [2, 3, 2]])
print(a)
b = np.sort(a, axis=1)
print(b)

[[5 4 6]
 [2 3 2]]
[[4 5 6]
 [2 2 3]]


In [148]:
#in-place sort
a.sort(axis=1)
a

array([[4, 5, 6],
       [2, 2, 3]])

In [149]:
#sorting with fancy indexing
a = np.array([4, 3, 1, 2])
j = np.argsort(a)
j

array([2, 3, 1, 0])

In [150]:
a[j]

array([1, 2, 3, 4])